### ISSUE TITLE
Task05

### ISSUE THREAD

**Issue by RicardoMarcal** [HenriqueMonti/healthquery#6]
Tela de vitória (`/quiz/resultado`) para substituir o "alert()"; vai mostrar o resultado (acertos/total) e ter 2 botões: um para voltar para o início (`/`) e outro para fazer o quiz novamente (redirect para `/quiz` + reset das variáveis do quiz).
Extra: implementar o [{#each}](https://svelte.dev/examples/each-blocks) para as alternativas do quiz

**Comment by HenriqueMonti** [comment]
Resolvido em [``433e650``](https://github.com/HenriqueMonti/healthquery/commit/433e650793dabe76c23e7700e71631acabad410a)
